import {MenuItem} from './menu.model';

export const MENU: MenuItem[] = [
  {
    id: 2,
    label: 'Dashboards',
    link: '/',
    icon: 'bx-home-circle',
  },
  {
    id: 120,
    label: 'Tests',
    link: '/',
    icon: 'bx-home-circle',
    userTypeKeys: ['STUDENT'],
  },
  {
    id: 50,
    label: 'Question Bank',
    link: '/question-bank/view',
    icon: 'bx-donate-blood',
    userTypeKeys: ['ACCOUNT_ADMIN', 'INSTRUCTOR'],
  },
  {
    id: 111,
    label: 'Tests',
    link: '/tests',
    icon: 'bx-spreadsheet',
    userTypeKeys: ['ACCOUNT_ADMIN', 'INSTRUCTOR'],
  },
  {
    id: 111,
    label: 'outComes',
    link: '/outcomes',
    icon: 'mdi mdi-bullseye-arrow',
    userTypeKeys: ['ACCOUNT_ADMIN', 'INSTRUCTOR'],
  },
  {
    id: 111,
    label: 'Awards',
    icon: 'bx-award ',
    userTypeKeys: ['ADMIN'],
    link: '/users/award',
  },
  {
    id: 8,
    label: 'Test Configuration',
    icon: 'bx-shape-polygon',
    userTypeKeys: ['ADMIN'],
    link: '/configurations',
  },
  {
    id: 140,
    label: 'Reports',
    icon: 'bx-log-in-circle ',
    parentId: 100,
    link: '/tests/reports',
    userTypeKeys: ['ADMIN'],
  },
  {
    id: 103,
    label: 'Students',
    icon: 'bxs-user-detail',
    userTypeKeys: ['ACCOUNT_ADMIN', 'INSTRUCTOR'],
    link: '/students',
  },
  {
    id: 104,
    label: 'Student Groups',
    icon: 'bx bxs-group',
    userTypeKeys: ['ACCOUNT_ADMIN', 'INSTRUCTOR'],
    link: '/student-groups',
  },
  {
    id: 103,
    label: 'Instructors',
    icon: 'mdi mdi-school',
    userTypeKeys: ['ACCOUNT_ADMIN'],
    link: '/instructors',
  },
  {
    id: 105,
    label: 'Accounts',
    link: '/users/account',
    icon: 'bx bxs-school',
    userTypeKeys: ['ADMIN'],
  },
  {
    id: 105,
    label: 'mailServer.mail',
    link: '/settings/mail-server',
    icon: 'bx bx-mail-send',
    userTypeKeys: ['ADMIN'],
  },
  {
    id: 105,
    label: 'systemApps.systemApps',
    link: '/settings/system-app',
    icon: 'dripicons-view-apps',
    userTypeKeys: ['ADMIN'],
  },
  {
    id: 105,
    label: 'packages.packages',
    link: '/settings/packages',
    icon: 'bx-cog',
    userTypeKeys: ['ADMIN'],
  },
  {
    id: 105,
    label: 'studentOnboarding.onboarding',
    link: '/onboarding',
    icon: 'bx-spreadsheet ',
    userTypeKeys: ['STUDENT'],
  },
];
